M48
; DRILL file {KiCad 6.0.11+dfsg-1~bpo11+1} date Sat 04 Mar 2023 12:31:59 PM PST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-03-04T12:31:59-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.11+dfsg-1~bpo11+1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X124.5Y-91.5
X124.5Y-120.0
X154.9Y-91.5
X154.9Y-120.0
T0
M30
